spring:
  application:
    name: book-service

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://book-db:5432/book
    username: postgres
    password: password

logging.level.com.romankudryashov.eventdrivenarchitecture: debug

inbox:
  processing:
    task:
      cron: "*/5 * * * * *"
      batch.size: 50
      subtask.timeout: 10000

user.check.use-streaming-data: false
